// ============================================================
// data.js  —  LEVELS & TERRAINS configuration
// ============================================================

const STARTERS = {
    pikachu:    { name: '피카츄',   img: 'assets/starters/25.png',  type: 'electric', x: -2 },
    bulbasaur:  { name: '이상해씨', img: 'assets/starters/1.png',   type: 'grass',    x: -2 },
    charmander: { name: '파이리',   img: 'assets/starters/4.png',   type: 'fire',     x: -2 },
    squirtle:   { name: '꼬부기',   img: 'assets/starters/7.png',   type: 'water',    x: -2 },
};

// 선택된 스타팅 포켓몬. 인트로 화면에서 설정됩니다.
let selectedStarter = null;

// 1세대 및 2세대 전체 지상 포켓몬 목록 (총 140종)
const ENEMY_POOL = [
    { name: '이상해꽃', img: '3.png', type: 'grass', isFlying: false },
    { name: '메가니움', img: '154.png', type: 'grass', isFlying: false },
    { name: '모래두지', img: '27.png', type: 'ground', isFlying: false },
    { name: '고지', img: '28.png', type: 'ground', isFlying: false },
    { name: '니드런♀', img: '29.png', type: 'poison', isFlying: false },
    { name: '니드리나', img: '30.png', type: 'poison', isFlying: false },
    { name: '니드퀸', img: '31.png', type: 'poison', isFlying: false },
    { name: '니드런♂', img: '32.png', type: 'poison', isFlying: false },
    { name: '니드리노', img: '33.png', type: 'poison', isFlying: false },
    { name: '니드킹', img: '34.png', type: 'poison', isFlying: false },
    { name: '삐삐', img: '35.png', type: 'fairy', isFlying: false },
    { name: '픽시', img: '36.png', type: 'fairy', isFlying: false },
    { name: '나인테일', img: '38.png', type: 'fire', isFlying: false },
    { name: '푸린', img: '39.png', type: 'normal', isFlying: false },
    { name: '푸크린', img: '40.png', type: 'normal', isFlying: false },
    { name: '뚜벅쵸', img: '43.png', type: 'grass', isFlying: false },
    { name: '냄새꼬', img: '44.png', type: 'grass', isFlying: false },
    { name: '라플레시아', img: '45.png', type: 'grass', isFlying: false },
    { name: '파라스', img: '46.png', type: 'bug', isFlying: false },
    { name: '파라섹트', img: '47.png', type: 'bug', isFlying: false },
    { name: '디그다', img: '50.png', type: 'ground', isFlying: false },
    { name: '닥트리오', img: '51.png', type: 'ground', isFlying: false },
    { name: '나옹', img: '52.png', type: 'normal', isFlying: false },
    { name: '페르시온', img: '53.png', type: 'normal', isFlying: false },
    { name: '고라파덕', img: '54.png', type: 'water', isFlying: false },
    { name: '골덕', img: '55.png', type: 'water', isFlying: false },
    { name: '망키', img: '56.png', type: 'fighting', isFlying: false },
    { name: '성원숭', img: '57.png', type: 'fighting', isFlying: false },
    { name: '가디', img: '58.png', type: 'fire', isFlying: false },
    { name: '윈디', img: '59.png', type: 'fire', isFlying: false },
    { name: '발챙이', img: '60.png', type: 'water', isFlying: false },
    { name: '수륙챙이', img: '61.png', type: 'water', isFlying: false },
    { name: '강챙이', img: '62.png', type: 'water', isFlying: false },
    { name: '케이시', img: '63.png', type: 'psychic', isFlying: false },
    { name: '윤겔라', img: '64.png', type: 'psychic', isFlying: false },
    { name: '후딘', img: '65.png', type: 'psychic', isFlying: false },
    { name: '알통몬', img: '66.png', type: 'fighting', isFlying: false },
    { name: '근육몬', img: '67.png', type: 'fighting', isFlying: false },
    { name: '괴력몬', img: '68.png', type: 'fighting', isFlying: false },
    { name: '모다피', img: '69.png', type: 'grass', isFlying: false },
    { name: '우츠동', img: '70.png', type: 'grass', isFlying: false },
    { name: '우츠보트', img: '71.png', type: 'grass', isFlying: false },
    { name: '꼬마돌', img: '74.png', type: 'rock', isFlying: false },
    { name: '데구리', img: '75.png', type: 'rock', isFlying: false },
    { name: '딱구리', img: '76.png', type: 'rock', isFlying: false },
    { name: '포니타', img: '77.png', type: 'fire', isFlying: false },
    { name: '날쌩마', img: '78.png', type: 'fire', isFlying: false },
    { name: '야돈', img: '79.png', type: 'water', isFlying: false },
    { name: '야도란', img: '80.png', type: 'water', isFlying: false },
    { name: '쥬쥬', img: '86.png', type: 'water', isFlying: false },
    { name: '쥬레곤', img: '87.png', type: 'water', isFlying: false },
    { name: '질퍽이', img: '88.png', type: 'poison', isFlying: false },
    { name: '질뻐기', img: '89.png', type: 'poison', isFlying: false },
    { name: '셀러', img: '90.png', type: 'water', isFlying: false },
    { name: '파르셀', img: '91.png', type: 'water', isFlying: false },
    { name: '롱스톤', img: '95.png', type: 'rock', isFlying: false },
    { name: '슬리프', img: '96.png', type: 'psychic', isFlying: false },
    { name: '슬리퍼', img: '97.png', type: 'psychic', isFlying: false },
    { name: '크랩', img: '98.png', type: 'water', isFlying: false },
    { name: '킹크랩', img: '99.png', type: 'water', isFlying: false },
    { name: '찌리리공', img: '100.png', type: 'electric', isFlying: false },
    { name: '붐볼', img: '101.png', type: 'electric', isFlying: false },
    { name: '아라리', img: '102.png', type: 'grass', isFlying: false },
    { name: '나시', img: '103.png', type: 'grass', isFlying: false },
    { name: '탕구리', img: '104.png', type: 'ground', isFlying: false },
    { name: '텅구리', img: '105.png', type: 'ground', isFlying: false },
    { name: '시라소몬', img: '106.png', type: 'fighting', isFlying: false },
    { name: '홍수몬', img: '107.png', type: 'fighting', isFlying: false },
    { name: '내루미', img: '108.png', type: 'normal', isFlying: false },
    { name: '코뿌리', img: '112.png', type: 'ground', isFlying: false },
    { name: '럭키', img: '113.png', type: 'normal', isFlying: false },
    { name: '덩쿠리', img: '114.png', type: 'grass', isFlying: false },
    { name: '캥카', img: '115.png', type: 'normal', isFlying: false },
    { name: '쏘드라', img: '116.png', type: 'water', isFlying: false },
    { name: '시드라', img: '117.png', type: 'water', isFlying: false },
    { name: '콘치', img: '118.png', type: 'water', isFlying: false },
    { name: '왕콘치', img: '119.png', type: 'water', isFlying: false },
    { name: '별가사리', img: '120.png', type: 'water', isFlying: false },
    { name: '아쿠스타', img: '121.png', type: 'water', isFlying: false },
    { name: '마임맨', img: '122.png', type: 'psychic', isFlying: false },
    { name: '루주라', img: '124.png', type: 'ice', isFlying: false },
    { name: '에레브', img: '125.png', type: 'electric', isFlying: false },
    { name: '마그마', img: '126.png', type: 'fire', isFlying: false },
    { name: '켄타로스', img: '128.png', type: 'normal', isFlying: false },
    { name: '잉어킹', img: '129.png', type: 'water', isFlying: false },
    { name: '라프라스', img: '131.png', type: 'water', isFlying: false },
    { name: '메타몽', img: '132.png', type: 'normal', isFlying: false },
    { name: '이브이', img: '133.png', type: 'normal', isFlying: false },
    { name: '샤미드', img: '134.png', type: 'water', isFlying: false },
    { name: '쥬피썬더', img: '135.png', type: 'electric', isFlying: false },
    { name: '부스터', img: '136.png', type: 'fire', isFlying: false },
    { name: '폴리곤', img: '137.png', type: 'normal', isFlying: false },
    { name: '암나이트', img: '138.png', type: 'water', isFlying: false },
    { name: '암스타', img: '139.png', type: 'water', isFlying: false },
    { name: '투구', img: '140.png', type: 'water', isFlying: false },
    { name: '투구푸스', img: '141.png', type: 'water', isFlying: false },
    { name: '잠만보', img: '143.png', type: 'normal', isFlying: false },
    { name: '미뇽', img: '147.png', type: 'dragon', isFlying: false },
    { name: '신뇽', img: '148.png', type: 'dragon', isFlying: false },
    { name: '뮤츠', img: '150.png', type: 'psychic', isFlying: false },
    { name: '리아코', img: '158.png', type: 'water', isFlying: false },
    { name: '장크로다일', img: '160.png', type: 'water', isFlying: false },
    { name: '꼬리선', img: '161.png', type: 'normal', isFlying: false },
    { name: '다꼬리', img: '162.png', type: 'normal', isFlying: false },
    { name: '레디바', img: '165.png', type: 'bug', isFlying: false },
    { name: '페이검', img: '167.png', type: 'bug', isFlying: false },
    { name: '초라기', img: '170.png', type: 'water', isFlying: false },
    { name: '랜턴', img: '171.png', type: 'water', isFlying: false },
    { name: '토게피', img: '175.png', type: 'fairy', isFlying: false },
    { name: '네티', img: '177.png', type: 'psychic', isFlying: false },
    { name: '보송송', img: '180.png', type: 'electric', isFlying: false },
    { name: '전룡', img: '181.png', type: 'electric', isFlying: false },
    { name: '마릴', img: '183.png', type: 'water', isFlying: false },
    { name: '마릴리', img: '184.png', type: 'water', isFlying: false },
    { name: '꼬지모', img: '185.png', type: 'rock', isFlying: false },
    { name: '왕구리', img: '186.png', type: 'water', isFlying: false },
    { name: '에이팜', img: '190.png', type: 'normal', isFlying: false },
    { name: '해너츠', img: '191.png', type: 'grass', isFlying: false },
    { name: '해루미', img: '192.png', type: 'grass', isFlying: false },
    { name: '누오', img: '195.png', type: 'water', isFlying: false },
    { name: '에브이', img: '196.png', type: 'psychic', isFlying: false },
    { name: '블래키', img: '197.png', type: 'dark', isFlying: false },
    { name: '야도킹', img: '199.png', type: 'water', isFlying: false },
    { name: '마자용', img: '202.png', type: 'psychic', isFlying: false },
    { name: '키링키', img: '203.png', type: 'normal', isFlying: false },
    { name: '피콘', img: '204.png', type: 'bug', isFlying: false },
    { name: '노고치', img: '206.png', type: 'normal', isFlying: false },
    { name: '강철톤', img: '208.png', type: 'steel', isFlying: false },
    { name: '블루', img: '209.png', type: 'fairy', isFlying: false },
    { name: '그랑블루', img: '210.png', type: 'fairy', isFlying: false },
    { name: '침바루', img: '211.png', type: 'water', isFlying: false },
    { name: '핫삼', img: '212.png', type: 'bug', isFlying: false },
    { name: '단단지', img: '213.png', type: 'bug', isFlying: false },
    { name: '헤라크로스', img: '214.png', type: 'bug', isFlying: false },
    { name: '마그마그', img: '218.png', type: 'fire', isFlying: false },
    { name: '마그카르고', img: '219.png', type: 'fire', isFlying: false },
    { name: '꾸꾸리', img: '220.png', type: 'ice', isFlying: false },
    { name: '메모드', img: '221.png', type: 'ice', isFlying: false },
    { name: '코랄섭', img: '222.png', type: 'water', isFlying: false },
    { name: '총어', img: '223.png', type: 'water', isFlying: false },
    { name: '대포무노', img: '224.png', type: 'water', isFlying: false },
    { name: '딜리버드', img: '225.png', type: 'ice', isFlying: false },
    { name: '무장조', img: '227.png', type: 'steel', isFlying: false },
    { name: '델빌', img: '228.png', type: 'dark', isFlying: false },
    { name: '헬가', img: '229.png', type: 'dark', isFlying: false },
    { name: '킹드라', img: '230.png', type: 'water', isFlying: false },
    { name: '코코리', img: '231.png', type: 'ground', isFlying: false },
    { name: '코리갑', img: '232.png', type: 'ground', isFlying: false },
    { name: '폴리곤2', img: '233.png', type: 'normal', isFlying: false },
    { name: '노라키', img: '234.png', type: 'normal', isFlying: false },
    { name: '배루키', img: '236.png', type: 'fighting', isFlying: false },
    { name: '카포에라', img: '237.png', type: 'fighting', isFlying: false },
    { name: '밀탱크', img: '241.png', type: 'normal', isFlying: false },
    { name: '해피너스', img: '242.png', type: 'normal', isFlying: false },
    { name: '라이코', img: '243.png', type: 'electric', isFlying: false },
    { name: '앤테이', img: '244.png', type: 'fire', isFlying: false },
    { name: '마기라스', img: '248.png', type: 'rock', isFlying: false }
];

// 1세대 및 2세대 전체 공중/유체 포켓몬 목록 (총 103종)
const FLYING_POOL = [
    { name: '버터플', img: '12.png', type: 'bug', isFlying: true },
    { name: '독침붕', img: '15.png', type: 'bug', isFlying: true },
    { name: '구구', img: '16.png', type: 'flying', isFlying: true },
    { name: '피죤', img: '17.png', type: 'flying', isFlying: true },
    { name: '피죤투', img: '18.png', type: 'flying', isFlying: true },
    { name: '깨비참', img: '21.png', type: 'flying', isFlying: true },
    { name: '깨비드릴조', img: '22.png', type: 'flying', isFlying: true },
    { name: '주뱃', img: '41.png', type: 'poison', isFlying: true },
    { name: '골뱃', img: '42.png', type: 'poison', isFlying: true },
    { name: '도나리', img: '49.png', type: 'bug', isFlying: true },
    { name: '콘팡', img: '48.png', type: 'bug', isFlying: true },
    { name: '파오리', img: '83.png', type: 'flying', isFlying: true },
    { name: '두두', img: '84.png', type: 'flying', isFlying: true },
    { name: '두트리오', img: '85.png', type: 'flying', isFlying: true },
    { name: '고오스', img: '92.png', type: 'ghost', isFlying: true },
    { name: '고우스트', img: '93.png', type: 'ghost', isFlying: true },
    { name: '팬텀', img: '94.png', type: 'ghost', isFlying: true },
    { name: '또가스', img: '109.png', type: 'poison', isFlying: true },
    { name: '또도가스', img: '110.png', type: 'poison', isFlying: true },
    { name: '스라크', img: '123.png', type: 'bug', isFlying: true },
    { name: '쁘사이저', img: '127.png', type: 'bug', isFlying: true },
    { name: '갸라도스', img: '130.png', type: 'water', isFlying: true },
    { name: '프테라', img: '142.png', type: 'rock', isFlying: true },
    { name: '프리져', img: '144.png', type: 'ice', isFlying: true },
    { name: '썬더', img: '145.png', type: 'electric', isFlying: true },
    { name: '파이어', img: '146.png', type: 'fire', isFlying: true },
    { name: '망나뇽', img: '149.png', type: 'dragon', isFlying: true },
    { name: '뮤', img: '151.png', type: 'psychic', isFlying: true },
    { name: '부부', img: '163.png', type: 'flying', isFlying: true },
    { name: '야부엉', img: '164.png', type: 'flying', isFlying: true },
    { name: '레디안', img: '166.png', type: 'bug', isFlying: true },
    { name: '아리아도스', img: '168.png', type: 'bug', isFlying: true },
    { name: '크로뱃', img: '169.png', type: 'poison', isFlying: true },
    { name: '토게틱', img: '176.png', type: 'fairy', isFlying: true },
    { name: '네이티오', img: '178.png', type: 'psychic', isFlying: true },
    { name: '통통코', img: '187.png', type: 'grass', isFlying: true },
    { name: '두코', img: '188.png', type: 'grass', isFlying: true },
    { name: '솜솜코', img: '189.png', type: 'grass', isFlying: true },
    { name: '왕자리', img: '193.png', type: 'bug', isFlying: true },
    { name: '니로우', img: '198.png', type: 'dark', isFlying: true },
    { name: '글라이거', img: '207.png', type: 'ground', isFlying: true },
    { name: '딜리버드', img: '225.png', type: 'ice', isFlying: true },
    { name: '만타인', img: '226.png', type: 'water', isFlying: true },
    { name: '스이쿤', img: '245.png', type: 'water', isFlying: true },
    { name: '루기아', img: '249.png', type: 'psychic', isFlying: true },
    { name: '칠색조', img: '250.png', type: 'fire', isFlying: true },
    { name: '세레비', img: '251.png', type: 'grass', isFlying: true },
    { name: '리자몽', img: '6.png', type: 'fire', isFlying: true }
];

const LEVELS = [
    { title: "Stage 1", terrain: 'grass', count: 3, flyingCount: 1 },
    { title: "Stage 2", terrain: 'ice',   count: 3, flyingCount: 1 },
    { title: "Stage 3", terrain: 'sky',   count: 3, flyingCount: 3 },
    { title: "Stage 4", terrain: 'lava',  count: 3, flyingCount: 1 },
    { title: "Stage 5", terrain: 'cave',  count: 3, flyingCount: 2 },
    { title: "Stage 6", terrain: 'electric', count: 4, flyingCount: 1 },
    { title: "Stage 7", terrain: 'psychic',  count: 4, flyingCount: 2 },
];

let terrainSeed = 0;

const TERRAINS = {
    grass: {
        name: "푸른 들판",
        bg: ["#1a4a2e", "#4a8f62", "#87ceeb"],
        color: "#2d6a4f", outColor: "#1a4a2e",
        func: (x) => Math.sin((x + terrainSeed) / 2) * 1.5 + Math.cos((x - terrainSeed) / 5) * 3 - 2
    },
    sky: {
        name: "구름 위 하늘",
        bg: ["#4ca1af", "#c4e0e5"],
        color: "rgba(255,255,255,0.8)", outColor: "#4ca1af",
        func: (x) => Math.sin((x + terrainSeed) / 4) * 2 + Math.sin((x - terrainSeed) / 1.5) * 0.5 - 2
    },
    lava: {
        name: "화산 용암",
        bg: ["#2a0000", "#5c0000", "#a52a2a"],
        color: "#1a0505", outColor: "#0a0202",
        func: (x) => Math.cos((x + terrainSeed) / 2.5) * 2.5 + Math.sin((x - terrainSeed) / 1.2) * 1 - 3
    },
    ice: {
        name: "얼음 설산",
        bg: ["#001f3f", "#005c99", "#cce6ff"],
        color: "#b3d9ff", outColor: "#001f3f",
        func: (x) => -4 + Math.abs(Math.sin((x + terrainSeed) / 3)) * 4 + Math.cos(x - terrainSeed) * 0.5
    },
    cave: {
        name: "어두운 동굴",
        bg: ["#0d0d0d", "#262626", "#404040"],
        color: "#595959", outColor: "#0d0d0d",
        func: (x) => Math.sin((x + terrainSeed) / 4) * Math.cos((x - terrainSeed) / 2) * 3 - 2
    },
    electric: {
        name: "발전소",
        bg: ["#1e1b4b", "#312e81", "#fbbf24"],
        color: "#1e1b4b", outColor: "#100e2b", // 언덕 아래를 배경 가장 어두운 남색 톤으로 통일
        func: (x) => Math.sin((x + terrainSeed) / 1.5) * 1.8 + Math.cos((x - terrainSeed) * 1.2) * 0.8 - 1
    },
    psychic: {
        name: "왜곡된 차원",
        bg: ["#3b0764", "#581c87", "#f472b6"],
        color: "#3e1b5d", outColor: "#1d0333", // 약간만 더 연하고 부드러운 딥 바이올렛 톤으로 조정
        func: (x) => Math.sin((x + terrainSeed) / 3) * 3 + Math.cos((x - terrainSeed) / 3) * 1.5 - 2
    }
};
